actor:
  log_std_max: 2
  log_std_min: -20
  output_dim: 6
env:
  action_dim: 3
  state_dim: 33
intermediate_dim: 512
iql:
  alpha: 0.005
  beta: 1.0
  eta_min: 1e-7
  gamma: 0.99
  learning_rate: 3e-6
  tau: 0.7
training:
  batch_size: 512
  epochs: 100
